### ISSUE TITLE
Bug: wrong balance in watch-only wallet

### ISSUE THREAD

**Issue by rubik** [m2049r/xmrwallet#145]
I synced a watch-only wallet and the application is showing the wrong balance.

Suppose the following transactions took place:
1. wallet receives 10 XMR
2. wallet receives 15 XMR
3. wallet sends 5 XMR

The correct balance over time is as follows:

| *Time* | *Amount* |
|--------|----------|
| 0      | 0        |
| 1      | 10       |
| 2      | 25       |
| 3      | 20       |

Monerujo would show that the balance is 30 XMR, since apparently it considers the last outbound transaction as inbound for some reason.

**Comment by skorokithakis** [comment]
I am getting the same bug. The last outbound transaction of 0.5ish XMR is shown as 30 XMR incoming.

**Comment by m2049r** [comment]
this is just how monero works. you will see the same behaviour in the official clients.

the reason for the inbound transactions you see is because of change from the network from your outbound transaction. there are numerous explanations on reddit and elsewhere.

the primary purpose of view-only wallets is for confirming incoming transactions (i.e. did i get my monero from the exchange/friend/whatever?) and NOT for watching the balance.
