### ISSUE TITLE
Vulnerabilities from "Mobile X-Ray"

### ISSUE THREAD

**Issue by NullPiotrException** [m2049r/xmrwallet#148]
Could you refer to the vulnerabilities found by Mobile X-Ray by High-Tech Bridge?
https://www.htbridge.com/mobile/?id=pt5hgh7v

They found 2 high, 1 medium and 3 low vulnerabilities in Monero.
Might make some users worried.

I know that "hardcoded data" is not a problem. But what about others? Especially the "high" and "medium" ones.

**Comment by m2049r** [comment]
i think the report is bogus in our context. but we can look into it.

**Comment by ehanoc** [comment]
The report is not bogus. 

We should not be storing wallet files in the external storage. 

It's just a matter of time until someone makes an app to scan the external storage for monero's wallet files, attempt logged passwords, corrupt, copy (for future decrypt attempts) or delete the files. 

Additionally, if i delete the app, i want my wallet files gone from the phone. You're still vulnerable for the same reasons described above even after you delete it.  

I can make a PR for this. 

I suggest we make a 2 step update of in.

(1) Move current users files to internal storage.
(2) Remove permission

**Comment by EarlOfEgo** [comment]
yes the reports aren't utterly bogus. It's just some static code analysis wich we can also use Lint for, however they outline some issues we might want to address.

The question is if the internal storage might be better for the wallet. I'm not sure, since it's also not really 100% secure and not only deleting the app could delete the wallet(Also if the user deletes stored files because there is no space left on the device, or whatever).
Yes someone could make an app to scan for Monero wallets on the device, but the same can happen on every Desktop(please correct me when I'm mistaken)

>Additionally, if i delete the app, i want my wallet files gone from the phone.
Yes that's an issue, but on the same side there are users that don't want that to happen.

So both versions have pros and cons, how about let the user choose? This could be an option in the settings menu, we just have to think what the default case should be.

**Comment by ehanoc** [comment]
It's not just static analysis, it's actually in line with android's security practices. And regarding your concerns :

- android sandboxes internal files from other processes access. A bit different from other OS's where things are more inside or outside user-space and permissions.

-  When deleting an app, users do want their files deleted. As designed...  Leaving traces of old files gives too much information behind and takes up space. It also limits your exposure from post - deleting. This is also crypto, users are expected  and responsible for backing up their seeds. Having them in the external storage, makes them open to have their files deleted, corrupted, copied and scanned anyway.

I don't see any reason for sensitive information to be available for every other process and to linger in a device long after the app is gone. 

There are scenarios where the internal storage does not protect you though ( worst in external) . 

If you lose your phone, and if someone is technically savy... If they root your phone, they can go through all storage. And if they know what Monero is ... And if they know your password to decrypt... 

I would vote to stick to the security guidelines and removing one permission would give a bit more confidence to users outside the community. 

External storage permission is unnecessary

**Comment by m2049r** [comment]
We have discussed this on multiple occasions in multiple forums. I still don't want to do this as I feel deleting wallets without warning is wrong.

Please submit examples of apps which actually delete real user generated data on uninstall. If we find good examples I will consider adding this as an option.

P.S. The quoted report is a static & automated analysis - not even based on the actual code but on the decompiled binary in the APK.

**Comment by ehanoc** [comment]
Every single android app has the contents of their private storage deleted upon uninstall. 

You can still recover your wallet after with your seed/keys if you choose to uninstall the app at any point. 

Security practices first with one less permission needed = more user confidence.

**Comment by NullPiotrException** [comment]
Couldn't agree more with ehanoc. In my opinion it should be a must-have to delete user generated data and config files in uninstall on ANY system. I wouldn't even make a prompt asking whether user wants to keep the files in case of Monerujo since Monero is about privacy and security.

The reason I like Monero is because privacy is the default, unlike with Zcash. We shouldn't concern with users' opinions and other apps. It's the devs who should decide what's best for users, as users might not be programatically and privacy-conscious. Security should come out of the box.
I don't think that AviD's rule of Usability which is:

> Security at the expense of usability, comes at the expense of security.

...applies to Monero. Just my opinion. I'm still grateful for your app.

**Comment by m2049r** [comment]
I know that every apps private storage is deleted upton uninstall - and exactly this fact is my problem with your proposition.

Reiterating the same arguments will not convince me otherwise. I _need_ you to show me real world apps which delete **unretrievable** user generated content upon uninstall (without warning).

> You can still recover your wallet after with your seed/keys if you choose to uninstall the app at any point.

This is simply not true. Your notes on transactions are gone forever along with all your transaction keys. Again: deleting this without warning is grossly negligent in my opinion.

> users are expected and responsible for backing up their seeds

Yes, expected. How can this be guaranteed? What exactly would I respond to a support request saying
- "I uninstalled monerujo for blablabla reason, and now I installed it again and my 50 Moneroj are gone. WTF? You owe me $20k."
- "Well sorry about that, but it is expected that you have your seed backed up."

This is silly.

> Security at the expense of usability, comes at the expense of security.

Yes it does. The focus of Monerujo is on usability in the security context of Monero. It's not easy. We need better suggestions than "External storage permission is unnecessary". I am sure there is a better solution.

> External storage permission is unnecessary

Probably it is - as soon as we have the "Export transaction list" function which exports your transactions as a CSV so you can keep your transaction records in Excel or the like.

>  the same can happen on every Desktop

This was also my comment the very first time this issue came up - and I have not received an answer to date. There is no "private storage" on the destop. Any virus/trojan/malware has access to all your files. I understand we can be better than Destop apps. But do we _need_ to be?

**Comment by ehanoc** [comment]
Dude, i understand you want users to keep their notes and not blame you for forgetting to backup their seeds & keys. That's cool. 

But why sacrifice a very basic and standard android security feature?

What are you going to tell them when someone writes a scanner for monero wallet files? You don't think someone is going to try to do that and attempt logged passwords? Or even copy, corrupt or delete those files anyway?

I guess we should also explain to them that when you delete the app, those files stay on the phone too, exposed and forgotten. 

No one should use mobile wallets for big amounts anyway... But as you say... users... . 

I guess we don't need to do better. Why not though? I don't get it. 

But anyway, as you were

**Comment by m2049r** [comment]
> But why sacrifice a very basic and standard android security feature?

Because: I don't know any app which deletes your generated content. (Maybe I don't know a whole lot of apps,) And so it may be a basic and standard feature, but users simply do not EXPECT this behaviour.

> I guess we should also explain to them that when you delete the app, those files stay on the phone too, exposed and forgotten.

This is an excellent suggestion - we should add this info/warning to the "create/recover screen" with an option somewhere to "remove all wallets". Then the user is in control. I love your idea! Will discuss it with my UX crew.

**Comment by ehanoc** [comment]
I think you're complicating here. You're going to confuse users with this. 

This generated content is part of the internal workings of the app, not technically "user generated". Almost every app has internal files that are deleted upon uninstall.

Just look at almost every other open source wallet app. The external storage is usually only offered for backups. And this makes sense because it's an explicit and conscious choice. 

The most secure option should always be the default.

**Comment by m2049r** [comment]
> I think you're complicating here. You're going to confuse users with this.

possibly.

there is a significant difference between technically generated and thus reproducable data and user created data - which is not reproducable.

please understand that you would be DESTROYING user data (tx keys & notes) by deleting upon uninstall. no other app does this.

**Comment by m2049r** [comment]
we are going with the "explain it to the user" approach. thank you for all the input!

**Comment by NullPiotrException** [comment]
Thanks for considering internal storage.

Just my closing thought, hope you don't mind. Imo the best solution would be keeping files in the internal storage. Telling users during wallet creation that they should copy the seed (in bold), store it offline and if they don't they might lose their funds. On uninstall users would be prompted that all the files will be destroyed and if they haven't saved the seed, they'll lose access to their funds and that they won't be able to prove that they sent a transaction without the files (so they shouldn't uninstall if they have some settlements in progress). Add an option to backup the data (so it's a bit user friendly) in external storage, but also inform users about consequences of that.

As a final note, you said you worry someone might make you responsible when they uninstall the app without saving the seed and lose access to their funds. Imo it's bogus if you just make all the prompts I suggested. On the other hand, someone might make you responsible when they get their data stolen because it was kept in the external storage. I wouldn't agree with that person but that seems more plausible and rational for me, than the first situation.

Anyway, thanks again for looking into this and using your time discussing the issue.

**Comment by ehanoc** [comment]
I'm sure there's more android engineers within the community that would point out that there is no surprise here that this gets flagged as high risk.

But fair enough, as you were.

**Comment by m2049r** [comment]
@einsteinsfool unfortunately there is no uninstall callback in android - otherwise i would have done exactly as you say from the beginning.

**Comment by KeeJef** [comment]
The scenario where a user deletes their wallet without having the seed is going to be far more common that the scenario where a a malicious party logs passwords scans phones for Monero wallets and decrypts. for me this is far less a security issue than it is a simple cost benefit analysis. i dont really want users coming to us every second day complaining about losing 30k because they uninstalled a app.
