### ISSUE TITLE
Password show in plain text

### ISSUE THREAD

**Issue by Forage** [m2049r/xmrwallet#285]
Why is the password, used to open the wallet, shown in plain text in the wallet details?! No mater how safe the user thinks he is, this should never be displayed again, anywhere, after having to type it to login to begin with. After the login dialogue, even the app should not know about the original password any longer. The longer the the app knows about it the more risk you take.

The user typed the password to open the wallet in the first place, why display it again? Why take that risk?

**Comment by m2049r** [comment]
since we are displaying the mnemonic seed there is no increased risk by showing the password. showing the "restore password" is necessary as the it usually not the actual password the user enters - and they need it to restore the wallet on a different device or after a full reset.

**Comment by jenniferberger** [comment]
@m2049r I do not agree with the risk evaluation. Sure the password should be unique but a glimpse on the password may reveal the pattern the user selected. And users tend to reuse passwords.
So i agree to not display the password (that was just entered to see the details)
Displaying the password-hash is important for backups.

**Comment by m2049r** [comment]
@jenniferberger i agree with you. but we don't have a "confirm password" field - do you think this may be a problem?

**Comment by Forage** [comment]
Glad to hear we can at least agree on the fact that this poses a risk.

Where/when do you think we might need a confirm password field?

**Comment by leafcutterant** [comment]
Request for re-open.

@m2049r, I believe the password discussed here is the user password defined by the user to protect the wallet (and specifically, in the context when you are creating or importing a wallet and are asked to define the password). It's not the wallet file restore password.

I agree with @Forage and @jenniferberger that displaying the user password is very bad security practice. Sure, when you create the wallet, at one time the mnemonic is shown on the screen. However, it's also possible that you are exposed to surveillance in differing degrees while you're on the mnemonic screen and while you're entering your pass. But more importantly, it threatens not only the security of your XMR, but also any other service where you use the same password, or recycle a part or the structure of it.

Going by proper attack vector assumptions, we should expect the worst and not display any sensitive information when it's not absolutely necessary.

If you worry about the user typing in a wrong password at import/creation and then losing access, then sure, a "Confirm password" field would solve exactly this.

**Comment by leafcutterant** [comment]
Again, I'd like to draw attention to the fact that the password is still displayed visibly upon wallet creation and you can't hide it.

Passwords displayed as readable test is a very bad security practice and I fail to understand why this was wontfixed.

**Comment by m2049r** [comment]
because you should be in a safe place when entering anything on the restore/create wallet screens. there will not be anyone looking at your screen in that situation. and if there is, they can see (take a photo of) your seed. just don't create wallets in public places. i understand all the arguments about "a password can by read by a glimpse and a seed cannot because it is long" - but i don't want to be cluttering the screen with two hidden password fields for someone who does not understand they should not be doing private stuff in public places.

**Comment by Forage** [comment]
If anything it would remove clutter because the only thing needed is to remove the password display altogether. There should be no way to display it at all.

**Comment by m2049r** [comment]
@Forage which screen are you talking about?

**Comment by Forage** [comment]
The secrets screen, the one where the password is displayed in plain sight below the seed.

**Comment by leafcutterant** [comment]
@m2049r I believe you're discounting quite a few things here.

* Being in a safe place is ideal, but life is anything but ideal and brings unwelcome situations all the time. If we can choose whether to disclose both the seed and the password  in a public place, or only the seed, which would be more beneficial?
* The Monero seed can only be used for accessing that wallet's balances, but a password probably has other uses as well. The password, a part of it, or a pattern that's present in it may be re-used by the user in other apps, wallets, lock screens, registrations, etc. Why do we want to disadvantage every user who doesn't use a completely unique password for Monerujo?
* Why is it imperative that the seed should be also displayed in a readable form? I don't know about you, but I usually restore my seed from a password manager so there's practically no use for me to see the seed in the process (it's already hidden in the password manager). I'd argue it would be much more secure to make the seed text box selectively revealing ("dots" by default, and have an eye icon that toggles between the dots and the actual text). Similarly, on the summary page after the restoration, I'd rather have all sensitive information hidden by default and a toggle icon if the user wants to inspect it.

>  i don't want to be cluttering the screen with two hidden password fields for someone who does not understand they should not be doing private stuff in public places.

* I really don't think a minor UI convenience should be a deciding factor when we're talking infosec. Even more so because about half of that screen is empty. Also, having to enter your password twice is standard practice in web registration forms, so basically everyone who uses the internet is familiar with it. It's not any more cluttering than having "SPEND MY SWEET MONEROJ" instead of "Send" (which, by the way, always brings a big smile to my face, please don't remove it).

(Edited to add a few sentences.)

**Comment by Forage** [comment]
Don't forget that for the app to be able to display passwords again means that the app needs to remember them for the duration of using the app.
Yes, a phone already needs to be compromised to be able to exploit this, and when this is the case your wallet might already be compromised without making use of an in memory password, but why increase the risk even more?

**Comment by m2049r** [comment]
there seems to be some confusion between the "create new wallet" screen with the "secrets" screen. most of this discussion seems to revolve around the latter. it does **not** show the user password (it used to, but it doesn't since quite some time). it shows the real wallet restore password (52 letters) below the seed. this is not something the user would use as a password anywhere else as it is generated by the app. afaict tell the user's passphrase is not shown anywhere in the app after creation. the reason for showing the seed & restore password, is so the user can note them down if they failed to do so on creation (or their records were destroyed). this is the same behaviour as the official CLI & GUI. there is an extra warning about safety before this info is shown and we have renamed the menu item to "secrets".

we can argue about showing the user passphrase on the "create new wallet" screen - but seriously: you need to be in a safe place when creating a wallet.

**Comment by Forage** [comment]
This only goes if you have set or changed a password after the introduction of "crazypass". 
I have never changed my password to prevent a hash being used and I've disabled it from ever happening with creating the .nocrazypass file.
So in my case my wallet password is really being displayed.

**Comment by m2049r** [comment]
.nocrazypass is not a supported mode. please do not reuse your passwords - that's really bad opsec.
