### ISSUE TITLE
Store the Ledger view key

### ISSUE THREAD

**Issue by skorokithakis** [m2049r/xmrwallet#707]
I'm having a lot of trouble with Ledger support, I can't even sync because syncing stops if the screen turns off. It's also very inconvenient to have to open the Ledger every time I want to open my wallet.

I think Monerujo would become a hundred times more usable if it could store the exported view key, and only require a connection to the Ledger when sending funds. Since the wallet already requires auth to open, there would be no loss of privacy, and would still preserve all the security of the Ledger.

**Comment by qwert95** [comment]
This would be really useful, I have a Ledger too and with other coins it usually works like this.

**Comment by ghost** [comment]
Additional supporting evidence that this is needed:

https://www.reddit.com/r/Monero/comments/lhw0cp/how_to_accept_xmr_for_payments_at_my_buisness/gn25i6g?utm_source=share&utm_medium=web2x&context=3

**Comment by m2049r** [comment]
> I'm having a lot of trouble with Ledger support, I can't even sync because syncing stops if the screen turns off. It's also very inconvenient to have to open the Ledger every time I want to open my wallet.

which screen turns off?

**Comment by skorokithakis** [comment]
The phone screen.

**Comment by m2049r** [comment]
the phone screen should actually stay on until sync is complete - are you sure it turns off by itself?

**Comment by skorokithakis** [comment]
Oh jeez, I can't believe this, the screen goes into half-brightness mode and I assumed it would turn off shortly, so I spent hours touching the screen every few seconds so it wouldn't lock, but it goes into half-brighness mode and stays on...

That's good to know, but it would still be much more convenient if I didn't have to use the Ledger every time I wanted to open the wallet. I'd gladly store the view key along the other encrypted data, so I would only need the Ledger if I wanted to send funds.

**Comment by Mansarde** [comment]
@skorokithakis 
In order to get a view key for the Monero wallet on your Ledger, you can use one of these two tools:

- https://github.com/Coinomi/bip39-coinomi
- https://github.com/LedgerHQ/app-monero/tree/master/tools/python

The first one is a simple HTML page, the other a Python CLI tool.
Both work offline, but the HTML page might be the simpler and faster solution.
If you enter your Ledger seed in one of these two tools, then it will show you the Monero/Electrum seed as well as the private view key.
You can then use this view key in Monerujo so that you don't have to connect the Ledger if you just want to monitor incoming transfers.

Just be careful to use these tools on a PC that is not connected to any network. Maybe booting from a Live-OS on a laptop and then use the HTML on there.

**Comment by skorokithakis** [comment]
Thanks, @Mansarde, but that's not very convenient, as I'd have to sync the chain twice (once to view and once to send. It's a good workaround, though.

**Comment by Mansarde** [comment]
Ah gotcha. I thought you mainly wanted to monitor because you mentioned the view key.
But totally overlooked the "exported view key" part. My bad.^^
Yeah that would actually be quite useful, I agree!
+1

**Comment by m2049r** [comment]
@Mansarde if you open the "show secrets" page you will see the ledger view key :) there's a copy icon next to it for convenience

**Comment by Mansarde** [comment]
@m2049r Oh shoot, that works with Ledger wallets as well? That's so much easier, thanks for letting me know! 😄

**Comment by m2049r** [comment]
about this issue: i don't think it's possible to implement what @skorokithakis is asking for (which would be awesome!!) in monerujo because of the way monero core works. the view key only sees incoming transactions & outgoing ones need the spend key - so we would need a two phase blockchain parsing process - once with only the view key and at some later point with the ledger plugged in to rescan the potential transactions with the spend key. this needs to be implemented (it's surely possible) in monero itself. please raise an issue there and monerujo will inherit the functionality if it's built.

**Comment by skorokithakis** [comment]
@m2049r Just to confirm, does this mean that the view key can't actually view outgoing transactions? That seems odd.

**Comment by m2049r** [comment]
yep @skorokithakis. in fact, outgoing transactions are seen as incoming transactions (with different amounts) because of the change generated.

**Comment by m2049r** [comment]
see https://www.getmonero.org/resources/user-guides/view_only.html

**Comment by skorokithakis** [comment]
Ah, that's unfortunate, thanks!
