### ISSUE TITLE
Wallet status :status critical

### ISSUE THREAD

**Issue by zsquared999** [m2049r/xmrwallet#765]
Std bad_alloc, null
This is said under public address and restore height after I've been logging in with the same password for a couple weeks. When trying to log in it says Check username/password Connection failed! Anybody have any solution?

**Comment by BigPabby79** [comment]
Exact same thing here.

**Comment by BigPabby79** [comment]
I used the wallet reset and it fixed it for me.

**Comment by juanpc2018** [comment]
same here, Wallet is useless.
2 different phones.

restored from keys, and failed to sync,
and again same error.

other phone was working ok,
pum, same error

**Comment by m2049r** [comment]
use the "wallet reset" option in the wallet list.
this issue is due to the cache file getting corrupted. no idea why this happens - it started happening after the node attack last year. using a different node may help. please report here if it does. which node are you using now?
monerujo itself does nothing with the cache file...

**Comment by juanpc2018** [comment]
> use the "wallet reset" option in the wallet list.
> this issue is due to the cache file getting corrupted. no idea why this happens - it started happening after the node attack last year. using a different node may help. please report here if it does. which node are you using now?
> monerujo itself does nothing with the cache file...

call me crazy, but i cannot wait hours to sync / reset the wallet every time i reboot the phone, close the app or open/close the wallet.
that´s insane...

gives an error: Node password error.
but the static Node i use does Not have password.
wallet does Not open.

private keys become corrupt, every time, everyday.

i´m using:
node.supportxmr.com:18081
the safest public Node, because it´s the same node used by 50% of the miners.
https://miningpoolstats.stream/monero

#2.
when recovering wallet from p.keys, IF restore height is set to 0, does Not search/sync,
must be 1, but wallet allows 0 to be set.
= crazy.

using Date should add a [x] to select Block# or Date YYYYMMDD or YYYY-MM-DD.

enter what ever you want, i figure it out later, it´s crazy.

having MM and DD it´s redundant, most people don´t remember that.
just the year is good enough to start searching,
there´s No need for such pin point accuracy.
bad luck if you have 2000-12-29
good luck if you have 2000-01-01

#3. seems to me your github was hacked, and the wallet now has a worm / malware / virus..
probably the new added code tries to send the wallet keys to a private server in the Node list.
but something in your walllet is preventing the funds getting stolen.
maybe the corrupt file is simply the keys packaged in a .zip or .txt ready to be sent to the private server with a password.
that´s the only logical reason.
and it´s waiting to connect to the proper server to stole the keys.

seems to me someone is trying to do an Exit Scam, and Blame you.
or you got greedy.

pretty clever, my congrats to the developer, good luck next time.

**Comment by juanpc2018** [comment]
found it, the proof
"im not crazy"
https://therecord.media/github-investigating-crypto-mining-campaign-abusing-its-server-infrastructure/

P.D. github is recording the login IP 
if you use a VPN, github will send a verification code to your email.

they have access to your email.
or they have a backdoor to Github.
or you are one of them.

**Comment by m2049r** [comment]
@juanpc2018 

ad 1: there must be something wrong with your phone - maybe really some malware. never heard of anyone else having these issues

ad 2: the year itself is a valid blockheight. the full YYYYMMDD is not. scanning a whole year takes a long time. esp. with a hardware wallet.

ad 3: unlikely. github is just a store for the code it is not included in the build process.

**Comment by juanpc2018** [comment]
i have 2 phones, 
1 offline LG V10 Android 7
1 online LG K40 Android 9

i only use the offline to store XMR
monerujo-1x17x2_universal.apk
was working ok. date 2/13/21
phone was stored, No battery.

Online phone had:
monerujo 1.16.2_Karmic Nodes_.apk 
was working ok.
date 1/13/21

someone complaining about monerujo being buggy, last week
in reddit, got me interested again...

so i decided to sync both phones to blockchain again,
same server. 
both failed at same time.
corrupt Show Secrets! 
cannot see wallet.
error server password.

i thought maybe was because XMR had another fork...
another change in the algorithm,
so i decided to update monerujo .apk

monerujo-2x0x6_universal.apk
offline phone is useless now. No Wallet, No Secrets. No error msg. just returns to main screen after password.
online works so far, but takes too much time to open the wallet.

seems the worm has a time bomb, 
both phones worked ok.
both failed at same time, offline and online.
this hack was Not planned overnight.
seems was done in steps, over a year of planning / look ahead.
but failed because i don´t use random servers.
i almost never open the wallet.
i guess / maybe there is only 1 fake server, "needle in a haystack."
maybe my ping is far from the fake server, 
fake server was designed to steal the keys when receives a password, 
probably the login & password are the keys from the infected wallet. No need to send a .zip or .txt
maybe fake server works ok, if does Not detect a password/key.
maybe they have my keys, but it´s a manual process to install the 1000´s of keys they collected,
 and move the coins to a new clean wallet.

looking on the DarkNet, there are many stolen BTC wallets, i have Not seen XMR yet,
but they try to sell the BTC keys,
seems they have Not moved the coins.
exept this:
https://therecord.media/hackers-move-760-million-from-the-2016-bitfinex-hack/

but they have several keys for sale, usually less than 1 BTC each,
i´ve seen many BTC keys for sale, -50% price or less. 
example: you pay $500usd. you get the equivalent of $2000usd. in BTC.

anyway...
i´m gonna recover the XMC fork coins from XMR keys,
http://theappecosystem.blogspot.com/2018/04/monero-tale-of-five-forks.html
https://t.me/xmccurrency

https://www.getmonero.org/downloads/
http://www.monero-classic.org/index_en.html#download

move all coins to Desktop Nodes,
store the wallet.dat file equivalent in a safe place,
and delete everything else.

bye bye
Android for Now.
