### ISSUE TITLE
Coin control yes/no?

### ISSUE THREAD

**Issue by plowsof** [m2049r/xmrwallet#938]
(Draft) research into the recent spam transactions shows the possible effect on reducing the effective ring size if one entity controls a certain % of recent outputs:
- https://github.com/Rucknium/misc-research/tree/main/Monero-Black-Marble-Flood/pdf
feather wallet has added coin control in version 2.0.0 (2022-07-08) [changelog](https://featherwallet.org/changelog/)
- Coin control: manual input selection
Monerujo now has PocketChange. its not that big of a leap to freeze/thaw certain outputs.

has your opinion changed since leaving this a comment on this bounty @m2049r? https://bounties.monero.social/posts/50/1-001m-look-and-spend-unspent-outputs-in-monerujo , is it still not going to happen?

one thing to note is that full chain membership proofs would deprecate the need for this.

**Comment by J0J0XMR** [comment]
m2049r says no: https://matrix.to/#/!OhIACQDGLqSrxxwtWU:monero.social/$2E1TyJCyjCVjmCHuyKLu4a9_UJCWtcL7pAcCWBqoqx4?via=matrix.org&via=monero.social&via=kernal.eu

**Comment by anhdres** [comment]
Two things:
- I don't speak for @m2049r and...
- We're always open to learn and/or discover that something we deemed not necessary turned out to be important and change minds about it.

That said, I see no real need for users to selectively choose which UTXOs to use in a transaction. If Monero itself is not "private enough" in a very small set of circumstances for a very particular set of users, this is something that should be addressed at the protocol level, and not at an app level. Monero's mantra is to protect users by default, having users manually taking care of their own protection is less than ideal.

And with PocketChange we're addressing the other need to select outputs that is not privacy-related.

Of course, I look forward to the FCMPs and getting past rings so all this is not even a thing.

**Comment by m2049r** [comment]
basically what @anhdres said
